=== SmpCat/Atrium_Profesor/swing-formulario/src/com/atrium/vista/datos.dtd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- DEFINICION DEL DOCUMENTO XML VALIDADOR DEL EJERCICIO DE FORMULARIO -->
<!-- autor: Juan Antonio Solves Garcia -->
<!-- version: 1.0 -->
<!-- fecha: 29-9-2016 -->
<!ELEMENT datos_formulario (fecha,autor,formulario) >
<!ELEMENT fecha (#PCDATA) >
<!ELEMENT autor (#PCDATA) >
<!ELEMENT formulario (nombre,apellido,calle,ciudad)>
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT apellido (#PCDATA) >
<!ELEMENT calle (#PCDATA) >
<!ELEMENT ciudad (#PCDATA) >

=== SmpCat/Atrium_Profesor/swing-formulario/src/com/atrium/vista/datos.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- DEFINICION DEL DOCUMENTO XML DEL EJERCICIO DE FORMULARIO -->
<!-- autor: Juan Antonio Solves Garcia -->
<!-- version: 1.0 -->
<!-- fecha: 29-9-2016 -->

<!DOCTYPE datos_formulario SYSTEM "./datos.dtd">
<datos_formulario>
	<fecha>29-9-2016</fecha>
	<autor>Profesor</autor>
	<formulario>
		<nombre>Juan Antonio</nombre>
		<apellido>Solves</apellido>
		<calle>Calle Java</calle>
		<ciudad>Sun MicroSystem</ciudad>
	</formulario>
</datos_formulario>
